# Generated by Django 3.2.5 on 2021-07-07 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_units', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
        ),
    ]
