# Generated by Django 3.2.5 on 2021-07-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=200, verbose_name='First name')),
                ('first_name_ru', models.CharField(blank=True, max_length=200, verbose_name='First name in Russian')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last name')),
                ('last_name_ru', models.CharField(blank=True, max_length=200, verbose_name='Last name in Russian')),
                ('middle_name_ru', models.CharField(blank=True, max_length=200, verbose_name='Middle name in Russian')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='Gender')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('email', models.EmailField(max_length=200, null=True, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Phone')),
                ('employment_date', models.DateField(verbose_name='Employment Date')),
                ('dismiss_date', models.DateField(blank=True, null=True, verbose_name='Dismiss Date')),
                ('position', models.CharField(max_length=254, verbose_name='Position')),
                ('seniority', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], max_length=20, verbose_name='Seniority')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Is Active?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('skills', models.ManyToManyField(blank=True, related_name='employees', to='employee.Skill')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
