# Generated by Django 3.2.5 on 2021-07-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
        ('employee', '0002_auto_20210707_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='unit.unit', verbose_name='Unit'),
        ),
    ]
