# Generated by Django 3.2.5 on 2021-07-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('roles_master', 'Roles Master'), ('manager', 'Manager')], default='employee', max_length=20, verbose_name='Role'),
        ),
    ]
