# Generated by Django 3.2.5 on 2021-07-07 19:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2050)], verbose_name='Year')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text', models.TextField(max_length=1000, verbose_name='Text')),
                ('is_done', models.BooleanField(default=False, help_text='Designates whether the goal should be treated as completed', verbose_name='Is goal done?')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='performance_review.performancereview', verbose_name='Review')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text', models.TextField(max_length=1000, verbose_name='Text')),
                ('is_done', models.BooleanField(default=False, help_text='Designates whether the criteria should be treated as completed', verbose_name='Is criteria done?')),
                ('start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('deadline', models.DateField(null=True, verbose_name='Deadline')),
                ('finish_date', models.DateField(null=True, verbose_name='Finish Date')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='performance_review.goal', verbose_name='Goal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text', models.TextField(max_length=2000, verbose_name='Text')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='performance_review.goal', verbose_name='Goals')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
