# Generated by Django 3.2.5 on 2021-07-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='goals',
            new_name='goal',
        ),
    ]
