# Generated by Django 3.2.5 on 2021-07-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_review', '0002_rename_goals_comment_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Finish Date'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
